---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: podplacement-webhook
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multiarch-operator
    app.kubernetes.io/part-of: multiarch-operator
    app.kubernetes.io/managed-by: kustomize
  name: podplacement-webhook
  namespace: system
