apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multiarch-tuning-operator
    app.kubernetes.io/instance: podplacement-webhook
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: multiarch-tuning-operator
  name: multiarch-tuning-operator-podplacement-webhook
