apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: multiarch-tuning-operator-controller-manager-service
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 9443
  - name: metrics
    port: 8443
    targetPort: 8443
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
