apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: multiarch-tuning-operator-controller-manager-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
