resources:
  - ./service.yaml
  - ./manifests.yaml

patches:
  - target:
      group: "admissionregistration.k8s.io"
      version: v1
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration
    patch: |-
      - op: replace
        path: /webhooks/0/clientConfig/service/name
        value: controller-manager-service
      - op: add
        path: /metadata/annotations
        value:
          "service.beta.openshift.io/inject-cabundle": "true"
