apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterpodplacementconfigs.multiarch.openshift.io
  annotations:
      service.beta.openshift.io/inject-cabundle: "true"