apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: multiarch-tuning-operator.v0.0.1
  namespace: openshift-multiarch-tuning-operator
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: PodPlacementConfig is the Schema for the podplacementconfigs API
      displayName: Pod Placement Config
      kind: PodPlacementConfig
      name: podplacementconfigs.multiarch.openshift.io
      version: v1alpha1
  description: The Multiarch Tuning Operator enhances the user experience for administrators
    of Openshift clusters  with multi-architecture compute nodes or Site Reliability
    Engineers willing to migrate from single-arch to multi-arch OpenShift. When diverse
    CPU architectures coexist within a cluster, the Multiarch Tuning Operator operator
    stands out as a pivotal tool to enhance efficiency and streamline operations such
    as architecture-aware scheduling of workloads.
  displayName: multiarch-tuning-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - multiarch-tuning-operator
  - pod-placement
  links:
  - name: Multiarch Tuning Operator
    url: https://github.com/openshift/multiarch-tuning-operator
  maturity: alpha
  minKubeVersion: 1.27.0
  provider:
    name: Red Hat
  version: 0.0.1
