apiVersion: multiarch.openshift.io/v1alpha1
kind: ClusterPodPlacementConfig
metadata:
  name: cluster
spec:
  logVerbosity: Normal
  namespaceSelector:
      matchExpressions:
        - key: multiarch.openshift.io/exclude-pod-placement
          operator: DoesNotExist
